const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('conversorAPI', {
  enviarArquivo: (caminho, formato, configuracoes, jobId) => ipcRenderer.send('processar-arquivo', caminho, formato, configuracoes, jobId),
  cancelarConversao: (jobId) => ipcRenderer.send('cancelar-conversao', jobId),
  obterOpcoes: (caminho) => ipcRenderer.invoke('opcoes-conversao', caminho),
  escolherPastaDestino: () => ipcRenderer.invoke('escolher-pasta-destino'),
  escolherImagemMarcaDagua: () => ipcRenderer.invoke('escolher-imagem-marca-dagua'),
  obterComponentes: () => ipcRenderer.invoke('componentes-disponiveis'),
  detalhesArquivo: (caminho) => ipcRenderer.invoke('detalhes-arquivo', caminho),
  lerCodigo: (caminho) => ipcRenderer.invoke('ler-codigo', caminho),
  ocrArquivo: (caminho, pasta, idioma) => ipcRenderer.invoke('ocr-arquivo', caminho, pasta, idioma),
  verificarAtualizacoes: () => ipcRenderer.invoke('verificar-atualizacoes'),
  obterPreferencias: () => ipcRenderer.invoke('obter-preferencias'),
  salvarPreferencias: (preferencias) => ipcRenderer.invoke('salvar-preferencias', preferencias),
  obterRegras: () => ipcRenderer.invoke('obter-regras'),
  salvarRegras: (regras) => ipcRenderer.invoke('salvar-regras', regras),
  receberArquivoRegra: (callback) => ipcRenderer.on('arquivo-regra', (_event, regra) => callback(regra)),
  mesclarPdfs: () => ipcRenderer.invoke('mesclar-pdfs'),
  separarPdf: (caminho, pasta) => ipcRenderer.invoke('separar-pdf', caminho, pasta),
  extrairPaginasPdf: (caminho, pasta, paginas) => ipcRenderer.invoke('extrair-paginas-pdf', caminho, pasta, paginas),
  girarPdf: (caminho, pasta) => ipcRenderer.invoke('girar-pdf', caminho, pasta),
  protegerPdf: (caminho, pasta, senha) => ipcRenderer.invoke('proteger-pdf', caminho, pasta, senha),
  otimizarPdf: (caminho, pasta, modo) => ipcRenderer.invoke('otimizar-pdf', caminho, pasta, modo),
  paginaWebParaPdf: (url, pasta) => ipcRenderer.invoke('pagina-web-para-pdf', url, pasta),
  extrairLegendas: (caminho, pasta, formato) => ipcRenderer.invoke('extrair-legendas', caminho, pasta, formato),
  extrairImagensPdf: (caminho, pasta) => ipcRenderer.invoke('extrair-imagens-pdf', caminho, pasta),
  receberStatus: (callback) => ipcRenderer.on('status-conversao', (_event, dados) => callback(dados)),
  receberProgresso: (callback) => ipcRenderer.on('progresso-conversao', (_event, percentual) => callback(percentual)),
  abrirNoExplorador: (caminho) => ipcRenderer.send('abrir-no-explorador', caminho)
});
