const { app, BrowserWindow, ipcMain, shell, dialog, clipboard } = require('electron');
const path = require('path');
const fs = require('fs/promises');
const ffmpeg = require('fluent-ffmpeg');
const ffmpegStatic = require('ffmpeg-static');
const sharp = require('sharp');
const { autoUpdater } = require('electron-updater');
const { PDFDocument, degrees } = require('pdf-lib');
const { optionsFor, extensionOf } = require('./conversion-catalog');
const { configureOptionalToolPath, run, runOutput, commandAvailable, componentStatus } = require('./system-tools');
const { createUpdateService } = require('./update-service');
const { createPreferencesService } = require('./preferences-service');
const { createPdfService } = require('./pdf-service');
const { createMediaService } = require('./media-service');
const { createRecognitionService } = require('./recognition-service');
const { createConversionService } = require('./conversion-service');

configureOptionalToolPath();
ffmpeg.setFfmpegPath(ffmpegStatic);
let mainWindow;
const outputDir = async (candidate) => candidate && await fs.stat(candidate).then((stat) => stat.isDirectory()).catch(() => false) ? candidate : path.join(app.getPath('desktop'));
const preferences = createPreferencesService({ getUserDataPath: () => app.getPath('userData'), sendRule: (rule) => mainWindow?.webContents.send('arquivo-regra', rule) });
const updates = createUpdateService({ updater: autoUpdater, getVersion: () => app.getVersion(), isPackaged: () => app.isPackaged, sendStatus: (payload) => mainWindow?.webContents.send('status-atualizacao', payload) });
const pdf = createPdfService({ PDFDocument, degrees, BrowserWindow, run, commandAvailable, outputDir });
const media = createMediaService({ ffmpeg, outputDir });
const recognition = createRecognitionService({ sharp, run, runOutput, commandAvailable, outputDir });
const conversion = createConversionService({ sharp, ffmpeg, run });

function createWindow() { const win = new BrowserWindow({ width: 1200, height: 800, minWidth: 900, minHeight: 600, icon: path.join(__dirname, '../../build/omnifree-icon.ico'), backgroundColor: '#0a0e1a', webPreferences: { preload: path.join(__dirname, '../preload/preload.js'), nodeIntegration: false, contextIsolation: true } }); win.setMenu(null); win.loadFile(path.join(__dirname, '../renderer/index.html')); mainWindow = win; }

ipcMain.handle('opcoes-conversao', (_event, filePath) => optionsFor(filePath));
ipcMain.handle('escolher-pasta-destino', async () => { const result = await dialog.showOpenDialog({ properties: ['openDirectory', 'createDirectory'] }); return result.canceled ? null : result.filePaths[0]; });
ipcMain.handle('escolher-imagem-marca-dagua', async () => { const result = await dialog.showOpenDialog({ properties: ['openFile'], filters: [{ name: 'Imagem', extensions: ['png', 'jpg', 'jpeg', 'webp', 'avif'] }] }); return result.canceled ? null : result.filePaths[0]; });
ipcMain.handle('componentes-disponiveis', () => componentStatus(ffmpegStatic));
ipcMain.handle('detalhes-arquivo', async (_event, filePath) => { const stat = await fs.stat(filePath); const details = { bytes: stat.size }; const extension = extensionOf(filePath); if (['png', 'jpg', 'jpeg', 'webp', 'avif', 'tif', 'tiff', 'bmp'].includes(extension)) { const meta = await sharp(filePath).metadata(); details.width = meta.width; details.height = meta.height; } if (extension === 'pdf') { const document = await PDFDocument.load(await fs.readFile(filePath)); details.pages = document.getPageCount(); } return details; });
ipcMain.handle('ler-codigo', (_event, input) => recognition.readCode(input));
ipcMain.handle('ocr-arquivo', (_event, input, folder, language) => recognition.ocr(input, folder, language));
ipcMain.handle('verificar-atualizacoes', () => updates.check());
ipcMain.handle('baixar-atualizacao', () => updates.download());
ipcMain.handle('instalar-atualizacao', () => updates.install());
ipcMain.handle('obter-preferencias', () => preferences.read());
ipcMain.handle('salvar-preferencias', (_event, value) => preferences.savePreferences(value));
ipcMain.handle('obter-regras', async () => (await preferences.read()).rules || []);
ipcMain.handle('salvar-regras', (_event, rules) => preferences.saveRules(rules));
ipcMain.handle('mesclar-pdfs', async () => { const selected = await dialog.showOpenDialog({ properties: ['openFile', 'multiSelections'], filters: [{ name: 'PDF', extensions: ['pdf'] }] }); return selected.canceled || selected.filePaths.length < 2 ? { canceled: true } : { output: await pdf.merge(selected.filePaths) }; });
ipcMain.handle('separar-pdf', (_event, input, folder) => pdf.split(input, folder));
ipcMain.handle('extrair-paginas-pdf', (_event, input, folder, pages) => pdf.extractPages(input, folder, pages));
ipcMain.handle('girar-pdf', (_event, input, folder) => pdf.rotate(input, folder));
ipcMain.handle('proteger-pdf', (_event, input, folder, password) => pdf.protect(input, folder, password));
ipcMain.handle('otimizar-pdf', (_event, input, folder, mode) => pdf.optimize(input, folder, mode));
ipcMain.handle('pagina-web-para-pdf', (_event, url, folder) => pdf.webToPdf(url, folder));
ipcMain.handle('extrair-legendas', (_event, input, folder, format) => media.extractSubtitles(input, folder, format));
ipcMain.handle('gerar-thumbnail', (_event, input, folder, time) => media.thumbnail(input, folder, time));
ipcMain.handle('extrair-imagens-pdf', (_event, input, folder) => pdf.extractImages(input, folder));
ipcMain.on('processar-arquivo', (event, input, target, settings, jobId) => conversion.process(event, input, target, settings, jobId));
ipcMain.on('cancelar-conversao', (_event, jobId) => conversion.cancel(jobId));
ipcMain.on('abrir-no-explorador', (_event, filePath) => { if (filePath) shell.showItemInFolder(filePath); });
ipcMain.on('copiar-caminho', (_event, filePath) => { if (filePath) clipboard.writeText(filePath); });
ipcMain.on('arrastar-arquivo', (event, filePath) => { if (filePath) event.sender.startDrag({ file: filePath, icon: path.join(__dirname, '../../build/omnifree-icon.png') }); });
app.whenReady().then(async () => { createWindow(); const settings = await preferences.read(); preferences.configureRules(settings.rules || []); if (app.isPackaged && settings.autoUpdates !== false) autoUpdater.checkForUpdatesAndNotify().catch((error) => console.warn('Não foi possível verificar atualizações:', error.message)); app.on('activate', () => { if (!BrowserWindow.getAllWindows().length) createWindow(); }); });
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
