const path = require('path');
const os = require('os');
const fs = require('fs/promises');
const { uniqueOutputPath } = require('./output-paths');
const { extensionOf } = require('./conversion-catalog');

function parsePages(value, count) { const pages = new Set(); for (const part of String(value || '').split(',')) { const match = part.trim().match(/^(\d+)(?:\s*-\s*(\d+))?$/); if (!match) continue; const first = Number(match[1]); const last = Number(match[2] || first); for (let page = Math.max(1, first); page <= Math.min(count, last); page += 1) pages.add(page - 1); } return [...pages].sort((a, b) => a - b); }
function createPdfService({ PDFDocument, degrees, BrowserWindow, run, commandAvailable, outputDir }) {
  const assertPdf = (input) => { if (extensionOf(input) !== 'pdf') throw new Error('Selecione um PDF primeiro.'); };
  return {
    async merge(files, folder) { const merged = await PDFDocument.create(); for (const file of files) { const source = await PDFDocument.load(await fs.readFile(file)); (await merged.copyPages(source, source.getPageIndices())).forEach((page) => merged.addPage(page)); } const output = await uniqueOutputPath(await outputDir(folder), 'OmniFree_unido', 'pdf'); await fs.writeFile(output, await merged.save()); return output; },
    async split(input, folder) { assertPdf(input); const source = await PDFDocument.load(await fs.readFile(input)); const outputs = []; for (const [index] of source.getPages().entries()) { const document = await PDFDocument.create(); document.addPage((await document.copyPages(source, [index]))[0]); const output = await uniqueOutputPath(await outputDir(folder), `OmniFree_pagina_${index + 1}`, 'pdf'); await fs.writeFile(output, await document.save()); outputs.push(output); } return outputs; },
    async extractPages(input, folder, pagesText) { assertPdf(input); const source = await PDFDocument.load(await fs.readFile(input)); const indexes = parsePages(pagesText, source.getPageCount()); if (!indexes.length) throw new Error('Informe páginas válidas, por exemplo: 1, 3-5.'); const document = await PDFDocument.create(); (await document.copyPages(source, indexes)).forEach((page) => document.addPage(page)); const output = await uniqueOutputPath(await outputDir(folder), 'OmniFree_paginas', 'pdf'); await fs.writeFile(output, await document.save()); return output; },
    async rotate(input, folder) { assertPdf(input); const document = await PDFDocument.load(await fs.readFile(input)); document.getPages().forEach((page) => page.setRotation(degrees((page.getRotation().angle + 90) % 360))); const output = await uniqueOutputPath(await outputDir(folder), 'OmniFree_girado', 'pdf'); await fs.writeFile(output, await document.save({ useObjectStreams: true })); return output; },
    async protect(input, folder, password) { assertPdf(input); if (!password) throw new Error('Informe uma senha para proteger o PDF.'); const output = await uniqueOutputPath(await outputDir(folder), 'OmniFree_protegido', 'pdf'); await run('qpdf', ['--encrypt', password, password, '256', '--', input, output]); return output; },
    async optimize(input, folder, mode = 'balanced') { assertPdf(input); const output = await uniqueOutputPath(await outputDir(folder), 'OmniFree_otimizado', 'pdf'); if (await commandAvailable('gswin64c')) { const preset = mode === 'small' ? '/screen' : mode === 'quality' ? '/printer' : '/ebook'; await run('gswin64c', ['-sDEVICE=pdfwrite', '-dCompatibilityLevel=1.4', `-dPDFSETTINGS=${preset}`, '-dNOPAUSE', '-dQUIET', '-dBATCH', `-sOutputFile=${output}`, input]); } else await run('qpdf', ['--stream-data=compress', '--object-streams=generate', input, output]); return output; },
    async extractImages(input, folder) { assertPdf(input); const destination = path.join(await outputDir(folder), `OmniFree_imagens_${Date.now()}`); await fs.mkdir(destination); await run('pdfimages', ['-all', input, path.join(destination, 'imagem')]); return destination; },
    async webToPdf(url, folder) { let parsed; try { parsed = new URL(url); } catch { throw new Error('Informe uma URL válida.'); } if (!['http:', 'https:'].includes(parsed.protocol)) throw new Error('Use apenas páginas HTTP ou HTTPS.'); const output = await uniqueOutputPath(await outputDir(folder), 'OmniFree_pagina_web', 'pdf'); const page = new BrowserWindow({ show: false, webPreferences: { sandbox: true } }); try { await page.loadURL(parsed.toString()); await fs.writeFile(output, await page.webContents.printToPDF({ printBackground: true, pageSize: 'A4' })); return output; } finally { if (!page.isDestroyed()) page.destroy(); } }
  };
}
module.exports = { createPdfService, parsePages };
